version: "3.7"
services:
  mqtt:
    build: ./mqtt
    ports:
      - "1885:1883"
      - "15674:15672"
      - "5674:5672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: unless-stopped

# "Producer" can be enabled to trigger a simple MQTT message to the RabbitMQ component
  producer:
    build: ./gateway-mqtt
    command: [ "python", "send.py" ]
    depends_on:
      - mqtt
